webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required

bp = Blueprint("admin", __name__, url_prefix="/admin")


@bp.route("/")
@admin_required
def admin_index():
    title = "Панель управления"
    return render_template("admin/admin_index.html", page_title=title)

webapp/user/views.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, current_user

from webapp.db import db
from webapp.user.models import User
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.utils import get_redirect_target

bp = Blueprint("user", __name__, url_prefix="/users")


@bp.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = "Авторизация"
    form = LoginForm()

    return render_template("user/login.html", page_title=title, form=form)


@bp.route("/process-login", methods=["POST"])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт")

            return redirect(get_redirect_target())

    flash("Неправильные имя или пароль")

    return redirect(url_for("user.login"))


@bp.route("/register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for("news.index"))

    form = RegistrationForm()
    title = "Регистрация"

    return render_template("user/registration.html", page_title=title, form=form)


@bp.route("/process-reg", methods=["POST"])
def process_reg():
    form = RegistrationForm()

    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role="user")
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash("Вы успешно зарегистрировались")

        return redirect(url_for("user.login"))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"Ошибка в поле {getattr(form, field).label.text}: {error}")
        return redirect(url_for("user.register"))


@bp.route("/logout")
def logout():
    logout_user()
    flash("Вы успешно разлогинились")

    return redirect(url_for("news.index"))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <title>{{ page_title }}</title>
  </head>
  <body>
      {% include "menu.html" %}
      <div class="container">
        <h1>{{ page_title }}</h1>
        {% block content %} {% endblock %}
      </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous">

      </script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous">

      </script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous">
      </script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Меню</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Главная</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link">Дароу, {{ current_user.username }}!</span>
          </li>
          {% if current_user.is_admin %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.admin_index')}}">Админка</a>
            </li>
          {%  endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout')}}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register')}}">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login')}}">Войти</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    {% endif%}
{% endwith %}